### ISSUE TITLE
Question about proxy

### ISSUE THREAD

**Issue by agutierrm** [genshen/ssh-web-console#10]
Hi there! 

Just watching your project, Im triying to proxy the ssh-web-console using Apache but it doesnt works. :-( Could you help me?
Im trying to use ProxyPass and ProxyPassReverse but for some reasong the app is always returning 301 redirect to /.
Maybe some tweak in config?

Thank you!

**Comment by genshen** [comment]
Hi, could you paste your apache config? And is there any noticeable log from `ssh-web-console` app?

I usually nginx to proxy the service (via `proxy_pass`), the nginx config is:
```nginx
server {
       listen         80;
       listen [::]:80;
       server_name    console.hpc.gensh.me;
       return         301 https://$http_host$request_uri;
}

server {
    listen       443 ssl;
    listen     [::]:443 ssl;
    server_name  console.hpc.gensh.me;
    access_log   logs/console.hpc.gensh.me.access.log;
    ssl_certificate      ../sslcrt/console.hpc.gensh.me.crt;
    ssl_certificate_key  ../sslcrt/console.hpc.gensh.me.key;

    location / {
        client_max_body_size 1024m;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host            $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:22222;
    }
}
```
In which, `proxy_set_header Upgrade` and `proxy_set_header Connection` here are used to config/process **websocket** connection (I don't know is there similar problem in apache?).

**Comment by agutierrm** [comment]
Hello genshen! Thanks for answering !

I see that you are serving on /. I think that my problem is that I would
like to serve under other path, ie /webssh/ .
So in this case I m not sure if I must change the conf parameters under
prod, so static_prefix, static_dir... Im not very
sure of understanding these settings. Have you ever tried to serve the
application under other path?

All examples I saw was related to serve under /. But, in my case, I have
the main website on / and under /webssh/ the app.

Thank you!!!!! Regards from Spain.

**Comment by genshen** [comment]
Currently, ssh-web-console does not support to config a prefix serving path like `/webssh`,  all servering path is under `/` (see [code](/genshen/ssh-web-console/blob/f21962dcae27ed10210df006b6fa0adc4a012bfd/src/routers/router.go#L54)).  This may be the reason why it always redirects to `/`.  

> Have you ever tried to serve the application under other path?  

I usually use different domains to deploy multiple sites under one Apache/nginx server.

**Comment by agutierrm** [comment]
Thank you genshen, I guess so, I dont know so much about go but I watch
some code in routers.go.

Thanks for your answer!!!! In any case thank you so much for your code. its
great!

**Comment by genshen** [comment]
Hi, @agutierrm, it can be a good suggestion to directly support serving path in ssh-web-console.  
Thus, I just updated the code to support this (see code in branch feature-prefix-serving-path).

However, it need you to build from source.  
Build steps:
1. build frontend.
edit file `web/package.json` and add field `"homepage": "/web-ssh/",` (see https://create-react-app.dev/docs/deployment/#step-1-add-homepage-to-packagejson).
Then build frontend via `REACT_APP_API_BASE_URL="/web-ssh" REACT_APP_ROUTER_BASE="/web-ssh/" yarn build` under directory `web`.
2. by following README to build go binary.
3. edit `conf/config.yaml` file (change `api_prefix: /web-ssh` and `static_prefix: /web-ssh/`) before running run ssh-web-console.

**Comment by agutierrm** [comment]
WOW!!!!!!!!!!!!!! Thank you very much!!! I will test it ASAP!!

Thank you so much
