### ISSUE TITLE
Cannot compile！

### ISSUE THREAD

**Issue by qidama666** [genshen/ssh-web-console#20]
Hello, I'm getting an error while compiling. It says that `github.com/genshen/ssh-web-console/statik` is missing in `route.go`. I noticed that this file is also not present in your project's source code. How should I handle this? I'm currently unable to compile.
![image](https://github.com/genshen/ssh-web-console/assets/61179927/0f1daab8-6ca6-4b1d-8b26-737b5431fcae)
![image](https://github.com/genshen/ssh-web-console/assets/61179927/b4c172c1-7c22-4404-9c57-8c8cbce496a8)

**Comment by genshen** [comment]
In the building document in the READMD.md, the command `statik --src=web/build` will generate a file in directory `statik`. Have you executed the command?
