### ISSUE TITLE
docker 安装不了啊

### ISSUE THREAD

**Issue by mojocn** [genshen/ssh-web-console#4]
当前的是一个前端项目吗?

**Comment by genshen** [comment]
try following commands:
```bash
$ docker pull genshen/ssh-web-console:latest
$ docker run -v ${PWD}/conf:/home/web/conf -p 2222:2222 --rm genshen/ssh-web-console
```
And in your browser, visit http://localhost:2222

**Comment by genshen** [comment]
> 当前的是一个前端项目吗?

该仓库是后端的代码，对应的前端请见 [webConsole](https://github.com/genshen/webConsole)。
