### ISSUE TITLE
希望增加黑白名单功能

### ISSUE THREAD

**Issue by DoubleShell** [genshen/ssh-web-console#9]

**Comment by genshen** [comment]
可以具体描述下需求吗？
是希望黑白名单限制（或仅允许）登录到特定的 几个ssh 服务器？

**Comment by DoubleShell** [comment]
抱歉，没说清楚，是希望能增加命令黑白名单限制，比如禁止rm等。

**Comment by DoubleShell** [comment]
最近在做相关项目，由于对xterm不太了解，能说一下怎么获取需要执行的一条完整命令的思路吗？

**Comment by genshen** [comment]
我想如果在前端进行黑名单限制/允许，可能需要针对 xterm 进行；或者在服务端进行过滤。  
不过，这两种可能都不好实现。因为 xterm 不是以 linux 命令为单位进行交互的（而是用来自用户输入的字符串流及服务器端返回的数据字符串流进行渲染的），后端也是数据流（来自浏览器用户的数据流和来自 ssh 服务器的数据流）。   
这就导致很难从数据流/字符串流中提取并过滤特定的命令（此外，还要防止误伤，例如 vim 编辑文件输入`rm` 这个字符串时，应该是需要让它通过的吧）。

当然，如果您有 linux 服务器的管理权限，可以通过配置服务器以达到黑白名单的目的（最简单的是给 rm 命令设置 alias，如 `alias rm='echo "do not use rm command"'`）。

**Comment by DoubleShell** [comment]
谢谢你的说明。
给命令设置alias确实可以解决部分问题，但因为我的需求是需要实现黑白名单，不仅仅是rm命令，而且支持后续拓展，所以还需要继续找解决方案。

我注意到jumpserver中实现了黑白名单功能，经测试黑白名单功能比较完善，正在研究jumpserver的源码。

**Comment by DoubleShell** [comment]
jumpserver的koko组件是通过解析ssh服务端的返回来获得命令输入和结果输出。
比如：输入一个字符“l”，则ssh服务会返回一个字符“l”，输入一个字符“s”，ssh服务返回一个字符“s”，输入回车字符，ssh服务会返回“ls”命令的执行结果；
输入字符“↑”，ssh服务会返回上次执行的命令。
其中对于“l”、“s”、“↑”输入，ssh返回的是命令的输入，回车后ssh返回的则是命令的执行结果，通过解析这两种情况，可以获取要执行的命令。
另外对于vim等操作，可以判断是否处于vim状态从而进行相应的操作。
